export enum InputType {
    TEXT,
    PASSWORD,
    LOCATION_SEARCH,
    DATE,
    DATE_RANGE,
    INCREMENTAL_SELECTOR,
    SWITCH,
    CVV,
    SEARCH,
    TEXT_DATE_INPUT,
    CHECKBOX,
    NUMBER
}